version: '3'

services:
  muse-mail:
    build: .
    container_name: muse-mail
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/server/data
