import Router from 'koa-router';
import { PersonalOSController } from '../controllers/PersonalOSController';

export const osRoutes = new Router();
const ctrl = new PersonalOSController();

osRoutes.get('/workspace', ctrl.workspace);
osRoutes.get('/search', ctrl.search);
osRoutes.get('/rules', ctrl.listRules);
osRoutes.post('/rules', ctrl.createRule);
osRoutes.put('/rules/:id', ctrl.updateRule);
osRoutes.delete('/rules/:id', ctrl.deleteRule);
osRoutes.post('/actions/state', ctrl.setActionState);
osRoutes.get('/memory', ctrl.listMemory);
osRoutes.post('/memory', ctrl.createMemory);
osRoutes.post('/memory/ai-manage', ctrl.aiManageMemory);
osRoutes.post('/memory/ai-apply', ctrl.applyAiMemoryPlan);
osRoutes.post('/accounts/ai-manage', ctrl.aiManageAccounts);
osRoutes.post('/accounts/ai-apply', ctrl.applyAiAccountPlan);
osRoutes.post('/proxies/ai-manage', ctrl.aiManageProxies);
osRoutes.post('/proxies/ai-apply', ctrl.applyAiProxyPlan);
osRoutes.post('/tokens/ai-manage', ctrl.aiManageTokens);
osRoutes.post('/tokens/ai-apply', ctrl.applyAiTokenPlan);
osRoutes.get('/memory/ingestion', ctrl.getMemoryIngestionState);
osRoutes.post('/memory/ingestion', ctrl.updateMemoryIngestionConfig);
osRoutes.post('/memory/ingestion/run', ctrl.runMemoryIngestionNow);
osRoutes.get('/agent/autonomy', ctrl.getAgentAutonomyState);
osRoutes.get('/agent/runtime', ctrl.getAgentRuntimeView);
osRoutes.get('/agent/memory', ctrl.getAgentMemoryState);
osRoutes.get('/agent/activity', ctrl.getAgentActivityState);
osRoutes.get('/agent/events', ctrl.listAgentEvents);
osRoutes.post('/agent/events', ctrl.createAgentEvent);
osRoutes.post('/agent/autonomy', ctrl.updateAgentAutonomyConfig);
osRoutes.post('/agent/autonomy/run', ctrl.runAgentAutonomyNow);
osRoutes.post('/agent/mode', ctrl.updateAgentExecutionMode);
osRoutes.post('/agent/memory/compact', ctrl.compactAgentMemory);
osRoutes.post('/agent/incidents', ctrl.reportAgentIncident);
osRoutes.get('/agent/profile', ctrl.listAgentProfile);
osRoutes.post('/agent/profile', ctrl.upsertAgentProfile);
osRoutes.get('/agent/skills', ctrl.listAgentSkills);
osRoutes.put('/memory/:id', ctrl.updateMemory);
osRoutes.delete('/memory/:id', ctrl.deleteMemory);
